export const constants = {
  routes: {
    LOGIN: '/login',
    OVERVIEW: '/overview',
    ORDERS: '/orders',
    BRANCHES: '/branches',
    STAFF: '/staff',
    ROLE_ACCESS: '/roles-access',
    REPORTS: '/reports',
    BRANDING: '/branding',
    SETTINGS: '/settings',
  },
  colors: {
    PRIMARY: 'offoOrange',
    SECONDARY: 'offoDark',
    ACCENT_GRAY: 'offoSlate',
    TEXT_DARK: 'offoTextDark',
    TEXT_LIGHT: 'offoTextLight',
    BG_LIGHT: 'offoPrimaryBg',
    BG_DARK: 'offoDark',
    BG_CARD_LIGHT: 'offoCardBgLight',
    BG_STAT_DARK: 'offoStatCardBgDark',
  },
  navbarHeight: '64px',
  sidebarWidth: '250px',
};